feat: adding option to select either paid or free
abhinavdc/cowin-pinger pull request #29
Opened 2021-08-03 07:42 UTC by harjyotkaur93

This can filter out vaccine search for either paid or free vaccines or can display both based on the centre types returned in the response

2021-08-03 12:37 UTC, abhinavdc requested changes
Can you roll-back all the formatting and whitespace changes and keep just the changes for centre-type filtering ?

Thanks for the PR.

2021-08-03 12:37 UTC, abhinavdc commented
Also can you change `centre-type` to something short and simple, like `type` ?

2021-08-03 13:30 UTC, harjyotkaur93 commented
> Can you roll-back all the formatting and whitespace changes and keep just the changes for centre-type filtering ?
> 
> Thanks for the PR.

Updated the PR

2021-08-09 03:34 UTC, abhinavdc approved these changes

2021-08-09 03:34 UTC, merged